name: Java 11 Maven clean package

on:
  workflow_call:
    secrets:
      GH_PACKAGE_REPO_PWD: 
       required: true
       
jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
# Typical Java 11 workflow steps
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
           
      - name: Build with Maven
        run: mvn clean package
        with:
          GH_PACKAGE_REPO_PASSWORD : ${{ secrets.GH_PACKAGE_REPO_PWD }}
    