name: Java 11 Maven clean package

on:
  workflow_call:
    secrets:
      GH_PACKAGE_REPO_PASSWORD: 
       required: true
       
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
           
      - name: Build with Maven
        run: mvn clean package
        env:
          GH_PACKAGE_REPO_PASSWORD : ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/cache@v3
        name: Cache target directory
        id: cache-target
        with:
          path: ~/target/*
          key: target
    