name: Update docker image

on: push

#on:
#  push:
#    branches:
#      - master

jobs:

  image_update:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGE_REPO_PASSWORD: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    steps:
      
      - name: Git Checkout
        uses: actions/checkout@v3
      
      - name: Run Creating Docker Image from Data-App repo
        run: ./ci/deploy.sh
      
